<a href="https://colab.research.google.com/github/YOONINJAE/winter_edu/blob/master/data_science_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# numpy class
print("Hello data science")

Hello data science


In [5]:
#  DAta science day 1
## Numpy class

In [7]:
import numpy as np
np.__version__

'1.19.5'

In [23]:
a=np.array([0,1,2,3,4],dtype = np.int16)
type(a)

numpy.ndarray

In [16]:
# a[0:3]\
a[0]

0

In [24]:
print(np.shape(a))
print(np.ndim(a))
print(np.size(a))
print(a.dtype)

(5,)
1
5
int16


In [28]:
array = np.array([[1,2,3],[2,3,4]], dtype=np.int32)
print(np.shape(array))
print(np.ndim(array))
print(np.size(array))
print(array.dtype)

(2, 3)
2
6
int32


In [29]:
array = np.array([range(i,i+3) for i in[1,4,7]],dtype = np.int32)
print(array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [35]:
array[0,:]
print(array[:,2])

[3 6 9]


In [39]:
array[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]], dtype=int32)

In [50]:
# 행렬 만들기
np.empty((2,3))
np.eye(2,3)
np.identity(2) # square matrix 정방행렬
np.zeros((3,3))
np.ones([3,5]) # tuple() list[]
np.full(shape = (3,5), fill_value=5)
np.full((5,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [53]:
np.array([[1,2],[3,5]])

array([[1, 2],
       [3, 5]])

In [70]:
#  array manipulation

np.arange(10)
np.arange(1,12,2)
arr_arange = np.arange(12)
np.reshape(arr_arange,(-1,3))   #-1부터 시작하면 알아서 맞춰줌 열만 정해주면 됨
# print(arr_arange)
np.arange(12).reshape(-1,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [75]:
x = np.arange(1,7).reshape(-1,3)
print(x)
x_flat = list(x.flat)

[[1 2 3]
 [4 5 6]]


[1, 2, 3, 4, 5, 6]

In [78]:
print(x)
x.T # translporse

[[1 2 3]
 [4 5 6]]


array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
x2d = np.array([[0],[1],[2]])
x = np.array([[[0],[1],[2]]])
print(x)
print(x2d)
print(np.shape(x2d), np.shape(x))
print(x.squeeze()) # 차원 감소시키기
print(x.squeeze(axis=0))
print(x.squeeze(axis=0).shape) # dimension reduction
print(x.squeeze(axis=2))
print(x.squeeze(axis=2).shape) #괄호 세개 있으면 3차원

[[[0]
  [1]
  [2]]]
[[0]
 [1]
 [2]]
(3, 1) (1, 3, 1)
[0 1 2]
[[0]
 [1]
 [2]]
(3, 1)
[[0 1 2]]
(1, 3)


In [110]:
a = np.array(np.arange(3))
b = np.array(np.arange(3,6))
print(a)
print(b)

c = np.vstack([a,b])
print(c)
print(np.hstack((a,b)))
print(np.column_stack((a,b)))

[0 1 2]
[3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]
[[0 3]
 [1 4]
 [2 5]]


In [120]:
x= np.arange(12)+1

mask = np.ones(len(x),dtype = bool)
mask[[0,2,4]] = False
print(mask)

print(x)

# 내가 원하는것만 뽑을때
x[mask] #data selection에 많이 쓰이는 방식이다.

[False  True False  True False  True  True  True  True  True  True  True]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([ 2,  4,  6,  7,  8,  9, 10, 11, 12])

In [121]:
len(x)

12

In [132]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

np.delete(arr,obj = 1, axis=0) # 0 행, 1열, 2 높이
np.delete(arr, obj = np.s_[::3],axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [141]:
a=np.array([[1,1],[2,2],[3,3]])
print(a)
a.shape
np.insert(a,1,5) #행에 넣기
np.insert(a,2,5, axis = 1) # 0 raw 1column

[[1 1]
 [2 2]
 [3 3]]


array([[1, 1, 5],
       [2, 2, 5],
       [3, 3, 5]])

In [150]:
print(a)
print(np.insert(a, 1, [2,4,6], axis = 1))
np.insert(a, [1], [2,4,6], axis=1)

[[1 1]
 [2 2]
 [3 3]]
[[1 2 1]
 [2 4 2]
 [3 6 3]]


array([[1, 2, 4, 6, 1],
       [2, 2, 4, 6, 2],
       [3, 2, 4, 6, 3]])

In [156]:
print (a)

a.flatten()
np.insert(a,2,[5,6])

[[1 1]
 [2 2]
 [3 3]]


array([1, 1, 5, 6, 2, 2, 3, 3])

In [161]:
# append
np.append([1,2,3], [[4,5,6],[7,8,9]])
np.append([[1,2,3], [4,5,6]],[[7,8,9]],axis=0) # [[]]두개는 2차원>? axis =1 쓸때 2D array로롤


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [163]:
np.unique([1,1,2,2,3,3])

array([1, 2, 3])

In [168]:
a=np.array([[1,0,0],[1,0,0],[2,3,4]])
print(a)
np.unique(a, axis =1)

[[1 0 0]
 [1 0 0]
 [2 3 4]]


array([[0, 0, 1],
       [0, 0, 1],
       [3, 4, 2]])

In [177]:
a = np.array(['rose', 'rose','iris','iris','sunflower'])
print(a)
u, indices = np.unique(a, return_index=True)
print(u)
print(indices)

['rose' 'rose' 'iris' 'iris' 'sunflower']
['iris' 'rose' 'sunflower']
[2 0 4]


In [184]:
A = np.arange(8).reshape(-1,4)
print(A)

np.flip(A)
np.flip(A, axis = 0)
np.flip(A, axis = 1)

[[0 1 2 3]
 [4 5 6 7]]


array([[3, 2, 1, 0],
       [7, 6, 5, 4]])

In [190]:
a=np.array([[1,4], [3,1]])
print(a)

np.sort(a,axis = 0)

[[1 4]
 [3 1]]


array([[1, 1],
       [3, 4]])

In [192]:
#  Random sampling
np.random.rand(3,2)

array([[0.69189363, 0.80680778],
       [0.70949713, 0.18982778],
       [0.29487096, 0.74742784]])

In [194]:
np.random.randint(1, 10, (3,3))

array([[4, 9, 7],
       [4, 8, 7],
       [5, 3, 6]])

In [205]:
np.random.randn(3,2) # 표준 정규분포 평균이 0이고 퍼짐의 정도가 1인 정규분포
np.random.normal(loc = 100, scale = 10, size = 10)
np.random.seed(830)
np.random.normal(100,30,size = 3 ) # seed를 넣어서 랜덤값 고정

array([114.32858157,  98.72723031, 107.38059832])

In [212]:
np.random.seed(830)
arr = np.random.randint(10, size  = 5)
arr


array([3, 4, 3, 9, 3])

In [224]:
arr_arg = np.arange(10)
print(arr_arg)
arr_arg_shf = np.random.shuffle(arr_arg)
print(arr_arg)

[0 1 2 3 4 5 6 7 8 9]
[9 6 2 8 3 1 5 0 7 4]


In [227]:
# descriptive / summary statistics
a = np.arange(4).reshape(-1,2)
print(a)
np.min(a, axis = 0)
np.min(a, axis = 1)

[[0 1]
 [2 3]]


array([0, 2])

In [231]:
print(a)
np.max(a)
np.max(a, axis=0) # axis = 0 column 열이다 ?????

[[0 1]
 [2 3]]


array([2, 3])

In [235]:
b= np.arange(5, dtype = float)
b[2] = np.nan  # missing value 처리기법
print(b)

np.max(b)
np.nanmax(b) # nan을 제외한 최대 값


[ 0.  1. nan  3.  4.]


4.0

In [241]:
a = np.array([[10,7,4],[3,2,1]])
print(a)

np.quantile(a, 0.5) #median
np.quantile(a, 0.5, axis=0)
np.quantile(a, 0.5, axis=1)

[[10  7  4]
 [ 3  2  1]]


array([7., 2.])

In [245]:
print(a)

np.mean(a)
np.median(a, axis = 0)
np.median(a, axis = 1)

[[10  7  4]
 [ 3  2  1]]


array([7., 2.])

In [258]:
a = np.random.rand(3,3)
print(a)

np.mean(a, axis=0)
np.median(a, axis = 0)
np.var(a, axis = 0)   # 분산, 표준오차 개념 잡기 
np.std(a, axis = 0)

print(np.corrcoef(a)) # Column끼리의 상관관계를 나타내는 근접할수록 1에 근접
print(np.cov(a))

[[0.50410642 0.36870367 0.0730111 ]
 [0.05366418 0.99758018 0.98312256]
 [0.5438358  0.64919199 0.35397832]]
[[ 1.         -0.73276089  0.78260466]
 [-0.73276089  1.         -0.14984648]
 [ 0.78260466 -0.14984648  1.        ]]
[[ 0.04860186 -0.08736983  0.02581227]
 [-0.08736983  0.29251322 -0.01212486]
 [ 0.02581227 -0.01212486  0.02238282]]


In [266]:
list1 = np.array([[1,2,3]])
list2 = np.array([[4,5,5]])

list1.shape

np.vstack([list1,list2])

np.concatenate([list1, list2], axis =0)


array([[1, 2, 3],
       [4, 5, 5]])

In [276]:
x = np.random.random((10,3))
print(x)
m = np.mean(x,axis=0)
print(m)

center_x = x-m  #dimension 알아서 맞춰서 계산해줌 ~
print(center_x)

[[0.2905743  0.45845661 0.29632976]
 [0.55371811 0.73234022 0.54295272]
 [0.15273924 0.76877084 0.07069582]
 [0.09200593 0.23806477 0.5879934 ]
 [0.68472606 0.69799531 0.09582799]
 [0.05251964 0.96041752 0.53397346]
 [0.16066313 0.11180047 0.42794225]
 [0.54810779 0.40705082 0.54859023]
 [0.19153743 0.36917695 0.38677031]
 [0.08727366 0.43339783 0.25946027]]
[0.28138653 0.51774713 0.37505362]
[[ 0.00918777 -0.05929053 -0.07872386]
 [ 0.27233158  0.21459309  0.1678991 ]
 [-0.12864729  0.2510237  -0.3043578 ]
 [-0.1893806  -0.27968237  0.21293978]
 [ 0.40333953  0.18024818 -0.27922563]
 [-0.22886689  0.44267039  0.15891984]
 [-0.1207234  -0.40594667  0.05288862]
 [ 0.26672126 -0.11069632  0.17353661]
 [-0.0898491  -0.14857018  0.01171669]
 [-0.19411287 -0.0843493  -0.11559335]]


In [284]:
center_x > 0.2
(center_x>0.2)| (center_x <0.200001)

arr_mask = center_x>0.1
print(arr_mask)

[[False False False]
 [ True  True  True]
 [False  True False]
 [False False  True]
 [ True  True False]
 [False  True  True]
 [False False False]
 [ True False  True]
 [False False False]
 [False False False]]
